<a href="https://colab.research.google.com/github/delphi12/NLP/blob/main/NLPAssignment_1_Task2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import re
import pandas as pd
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

**Input Answers**

In [30]:
input_answers = open('STS2016.input.answer-answer.txt','r')
input_headlines = open('STS2016.input.headlines.txt','r')
input_plagiarism = open('STS2016.input.plagiarism.txt','r')
input_postediting = open('STS2016.input.postediting.txt','r')
input_questions = open('STS2016.input.question-question.txt','r')

#Reading content from the text file
content = input_answers.readlines()

#Stripping each line in the content
content = [x.strip() for x in content]

#Removing the URL and unnecessary data from the text
content_split = [i.split('\tStack')[0] for i in content]

#Splitting each line into two sentences by removing tab space
result = [item.split('\t') for item in content_split]
#print(len(result))

In [33]:
#Creating a dataframe with the sentence list
import pandas as pd
df=pd.DataFrame(result)
df.columns = ["sentence1","sentence2"]
#df

In [34]:
#Removing stopwords from the dataframe columns
stop = stopwords.words('english')
df['s1_cleaned'] = df['sentence1'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop)]))
df['s2_cleaned'] = df['sentence2'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop)]))

In [37]:
#Printing the dataframe into a list
list_answers=df.values.tolist()
#print(list_answers)

#Creating two lists with the cleaned columns from the dataframe
sentence1=[]
sentence2=[]
for i in list_answers:
  sentence1.append(i[2])
  sentence2.append(i[3])


print(sentence1)
print(sentence2)

['Tasting reliable way.', 'I think probably depends money.', "You need read lot know like don't.", 'Obviously, best book depends lot looking for.', "I've problem.", 'If sure it, all.', 'It deciding get others do.', 'You need add resume position had.', 'I remained banyan tree, exhausted daily ritual dragooning men every two hours.', 'There ton examples online.', 'The way fine.', 'I think both.', "It's good idea tailor CV and/or resume position apply for.", 'So proposed answer "yes".', 'There things do:', 'In US, depend school.', 'I would say it, advised.', 'There reason worry.', 'You need know everything.', 'You need know everything.', 'It rather depends country in.', 'Does page answer question?', 'The two things really help are:', 'You answered question.', "You need read lot know like don't.", 'Cooking depends type sauce cooking.', 'You answered question.', 'How I proceed this?', "There's also string made of.", 'Unofficially not.', "If want use certain technique, that's part training p

**Headlines**

In [41]:
#For Headlines
content_headlines = input_headlines.readlines()
content_h = [x.strip() for x in content_headlines]
content_headlines = [i.split('\tEurope Media')[0] for i in content_h]
result_headlines = [item.split('\t') for item in content_headlines]
df_headlines=pd.DataFrame(result_headlines)
df_headlines.columns = ["headline1","headline2"]
stop = stopwords.words('english')
df_headlines['h1_cleaned'] = df_headlines["headline1"].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop)]))
df_headlines['h2_cleaned'] = df_headlines['headline2'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop)]))
list_headlines=df_headlines.values.tolist()
headline1=[]
headline2=[]
for i in list_headlines:
 headline1.append(i[2])
 headline2.append(i[3])

 #print(list_headlines)

**Plagiarism**

In [56]:
#For Plagiarism
content_plagiarism = input_plagiarism.readlines()
content_p = [x.strip() for x in content_plagiarism]
content_plagiarism = [i.split('\tA Corpus')[0] for i in content_p]
result_plagiarism = [item.split('\t') for item in content_plagiarism]
df_plagiarism=pd.DataFrame(result_plagiarism)
df_plagiarism.columns = ["plag1","plag2"]
stop = stopwords.words('english')
df_plagiarism['p1_cleaned'] = df_plagiarism["plag1"].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop)]))
df_plagiarism['h2_cleaned'] = df_plagiarism['plag2'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop)]))
list_plagiarism=df_plagiarism.values.tolist()
plag1=[]
plag2=[]
for i in list_plagiarism:
 plag1.append(i[2])
 plag2.append(i[3])

**Post Editing**

In [44]:
#For PostEditing
content_postediting = input_postediting.readlines()
content_po = [x.strip() for x in content_postediting]
content_postediting = [i.split('\tEAMT11')[0] for i in content_po]
result_postediting = [item.split('\t') for item in content_postediting]
df_postediting=pd.DataFrame(result_postediting)
df_postediting.columns = ["p1","p2"]
stop = stopwords.words('english')
df_postediting['pe1_cleaned'] = df_postediting["p1"].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop)]))
df_postediting['pe2_cleaned'] = df_postediting['p2'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop)]))
list_postediting=df_postediting.values.tolist()
pe1=[]
pe2=[]
for i in list_postediting:
 pe1.append(i[2])
 pe2.append(i[3])

**Question**

In [45]:
#For Question
content_question = input_questions.readlines()
content_q = [x.strip() for x in content_question]
content_question = [i.split('\tStackExchange')[0] for i in content_q]
result_questions = [item.split('\t') for item in content_question]
df_questions=pd.DataFrame(result_questions)
df_questions.columns = ["question1","question2"]
stop = stopwords.words('english')
df_questions['q1_cleaned'] = df_questions['question1'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop)]))
df_questions['q2_cleaned'] = df_questions['question2'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop)]))
list_questions=df_questions.values.tolist()
question1=[]
question2=[]
for i in list_questions:
 question1.append(i[2])
 question2.append(i[3])

**SBERT**

In [46]:
pip install -U sentence-transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.8/132.8 kB 2.9 MB/s eta 0:00:00


In [47]:
from sentence_transformers import SentenceTransformer
def sbert(sent1, sent2):
  sbert_model = SentenceTransformer('bert-base-nli-mean-tokens')
  embeddings1 = sbert_model.encode(sent1, convert_to_tensor=True)
  embeddings2 = sbert_model.encode(sent2, convert_to_tensor=True)
  return embeddings1, embeddings2

In [48]:
s1_embeddings, s2_reshaped = sbert(sentence1, sentence2)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.95k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/625 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/399 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [49]:
h1_embeddings, h2_embeddings = sbert(headline1, headline2)

In [57]:
p1_embeddings, p2_embeddings = sbert(plag1, plag2)

In [51]:
pe1_embeddings, pe2_embeddings = sbert(pe1, pe2)

In [52]:
q1_embeddings, q2_embeddings = sbert(question1, question2)

In [58]:
from sentence_transformers import SentenceTransformer, util
def c_score(embed1,embed2):
  cosine_scores = util.cos_sim(embed1, embed2)
  return cosine_scores

In [59]:
#Cosine similarity for input.answer-answer
ans_cosine = c_score(s1_embeddings, s2_reshaped)
print(ans_cosine)
ans_cosine_list= ans_cosine.tolist()

#Writing the cosine similarity to a file
ans= open(r'answerCosine.txt', 'w')
for item in ans_cosine_list:
  for i in item:
    ans.write("%s\n" %i)

tensor([[0.8260, 0.4147, 0.7210,  ..., 0.2443, 0.7323, 0.5721],
        [0.4114, 0.7525, 0.4157,  ..., 0.4850, 0.4507, 0.5828],
        [0.4293, 0.5393, 0.4673,  ..., 0.3492, 0.4164, 0.5430],
        ...,
        [0.7721, 0.6640, 0.9010,  ..., 0.5180, 0.7894, 0.6834],
        [0.6686, 0.5056, 0.7178,  ..., 0.3205, 0.7383, 0.6449],
        [0.6232, 0.7364, 0.6198,  ..., 0.4503, 0.6146, 0.6934]])


In [60]:
#Cosine similarity for input.headlines
head_cosine = c_score(h1_embeddings, h2_embeddings)
print(head_cosine)
head_cosine_list= head_cosine.tolist()

head= open(r'headlinesCosine.txt', 'w')
for item in head_cosine_list:
  for i in item:
    head.write("%s\n" %i)

tensor([[0.9678, 0.3447, 0.3597,  ..., 0.3109, 0.3296, 0.3926],
        [0.3399, 0.7423, 0.3432,  ..., 0.4844, 0.3962, 0.4508],
        [0.3775, 0.3204, 0.9688,  ..., 0.2501, 0.4908, 0.3502],
        ...,
        [0.3592, 0.5229, 0.3086,  ..., 0.7481, 0.5557, 0.1332],
        [0.3566, 0.3733, 0.3973,  ..., 0.6234, 0.7432, 0.2017],
        [0.1916, 0.3466, 0.2201,  ..., 0.4295, 0.2622, 0.1847]])


In [61]:
#Cosine similarity for input.plagiarisgm
plag_cosine = c_score(p1_embeddings, p2_embeddings)
print(plag_cosine)
plag_cosine_list= plag_cosine.tolist()

plag= open(r'plagiarismCosine.txt', 'w')
for item in plag_cosine_list:
  for i in item:
    plag.write("%s\n" %i)

tensor([[0.5605, 0.6642, 0.6697,  ..., 0.5815, 0.5128, 0.9224],
        [0.4786, 0.9731, 0.6294,  ..., 0.7003, 0.6590, 0.6485],
        [0.7043, 0.6815, 0.6293,  ..., 0.6304, 0.6998, 0.8524],
        ...,
        [0.6619, 0.6996, 0.5349,  ..., 0.6591, 0.6800, 0.5871],
        [0.4889, 0.5741, 0.4539,  ..., 0.5823, 0.5903, 0.3900],
        [0.7285, 0.5484, 0.4980,  ..., 0.4928, 0.6731, 0.5279]])


In [62]:
#Cosine similarity for input.postediting
pe_cosine = c_score(pe1_embeddings, pe2_embeddings)
print(pe_cosine)
pe_cosine_list= pe_cosine.tolist()

pe= open(r'posteditingCosine.txt', 'w')
for item in pe_cosine_list:
  for i in item:
    pe.write("%s\n" %i)

tensor([[0.8743, 0.3683, 0.2401,  ..., 0.1662, 0.1286, 0.2442],
        [0.4061, 1.0000, 0.3198,  ..., 0.1320, 0.1992, 0.4408],
        [0.3246, 0.3198, 1.0000,  ..., 0.1589, 0.3980, 0.2451],
        ...,
        [0.3205, 0.1562, 0.1890,  ..., 0.9552, 0.4597, 0.2425],
        [0.3543, 0.2106, 0.3985,  ..., 0.4294, 0.9542, 0.2869],
        [0.1512, 0.3474, 0.3583,  ..., 0.1675, 0.2910, 0.4807]])


In [63]:
cosine_scores = util.cos_sim(s1_embeddings, s2_reshaped)

#Output the pairs with their score
for i in range(len(sentence1)):
    print("{} \t\t {} \t\t Score: {:.4f}".format(sentence1[i], sentence2[i], cosine_scores[i][i]))

Tasting reliable way. 		 The way fine. 		 Score: 0.8260
I think probably depends money. 		 It depends country. 		 Score: 0.7525
You need read lot know like don't. 		 You know. 		 Score: 0.4673
Obviously, best book depends lot looking for. 		 The answer depend course looking vacation. 		 Score: 0.4678
I've problem. 		 I problem you. 		 Score: 0.9596
If sure it, all. 		 Also, die, repay, know helps. 		 Score: 0.5804
It deciding get others do. 		 What grow more? 		 Score: 0.6320
You need add resume position had. 		 You may want it, process given work within. 		 Score: 0.7103
I remained banyan tree, exhausted daily ritual dragooning men every two hours. 		 I remained banyan tree, exhausted daily ritual herding cats every two hours. 		 Score: 0.8621
There ton examples online. 		 There's ton variables: 		 Score: 0.6167
The way fine. 		 It you. 		 Score: 0.7896
I think both. 		 I think need double-entry bookkeeping. 		 Score: 0.4282
It's good idea tailor CV and/or resume position apply for. 	

In [64]:
print("answers")
print(s1_embeddings.shape)
print(s2_reshaped.shape)
print("headlines")
print(h1_embeddings.shape)
print(h2_embeddings.shape)
print("plagiarism")
print(p1_embeddings.shape)
print(p2_embeddings.shape)
print("postediting")
print(pe1_embeddings.shape)
print(pe2_embeddings.shape)
print("questions")
print(q1_embeddings.shape)
print(q2_embeddings.shape)

answers
torch.Size([1572, 768])
torch.Size([1572, 768])
headlines
torch.Size([1498, 768])
torch.Size([1498, 768])
plagiarism
torch.Size([1271, 768])
torch.Size([1271, 768])
postediting
torch.Size([3287, 768])
torch.Size([3287, 768])
questions
torch.Size([1555, 768])
torch.Size([1555, 768])


In [65]:
import numpy as np
s1_reshaped = np.reshape(s1_embeddings, (-1, 1))
s2_reshaped = np.reshape(s2_reshaped, (-1, 1))

**Universal Sentence Encoder**

In [67]:
!pip3 install --upgrade tensorflow-gpu
# Install TF-Hub.
!pip3 install tensorflow-hub

  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [ ]:
import tensorflow as tf
import tensorflow_hub as hub
import numpy as np
module_url = "https://tfhub.dev/google/universal-sentence-encoder/4"
model = hub.load(module_url)
print ("module %s loaded" % module_url)